model: 'DarkNet53_YOLOv3'
dataset_name: 'Pascal'
classes: 20
in_channels: 3
train_path: '/mnt/det_train'
val_path: '/mnt/det_valid'
names: '/dataset/detection/names/pascal_voc.txt'
input_size: 416

workers: 4
epochs: 500
batch_size: 8

save_freq: 1
save_dir: './saved'
gpus: -1

backbone: 'DarkNet'
varient: 53

optimizer: 'adam'
optimizer_options:
  lr: 1e-3

loss: 'yolo_loss'

trainer_options:
  check_val_every_n_epoch: 5

experimental_options:
  os: 'windows'
  callbacks:
    - 'SWA'